In [1]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 34.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 53.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 57.3 MB/s eta 0:00:00


In [2]:
!pip install sacremoses

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 880.6/880.6 kB 15.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895241 sha256=b41505a51cbeb2b8c065179437010e5e401631d803718bf6f12928e4d2978a35
  Stored in directory: /root/.cache/pip/wheels/00/24/97/a2ea5324f36bc626e1ea0267f33db6aa80d157ee977e9e42fb
Successfully built sacremoses


In [3]:
import torch
from transformers import AutoTokenizer, TransfoXLForSequenceClassification

In [4]:
tokenizer = AutoTokenizer.from_pretrained("transfo-xl-wt103")
model = TransfoXLForSequenceClassification.from_pretrained("transfo-xl-wt103")

Some weights of the model checkpoint at transfo-xl-wt103 were not used when initializing TransfoXLForSequenceClassification: ['crit.out_layers.3.bias', 'crit.out_layers.0.weight', 'crit.cluster_weight', 'crit.out_layers.2.weight', 'crit.cluster_bias', 'crit.out_layers.1.weight', 'crit.out_projs.0', 'crit.out_projs.2', 'crit.out_layers.3.weight', 'crit.out_layers.1.bias', 'crit.out_projs.1', 'crit.out_layers.0.bias', 'crit.out_layers.2.bias', 'crit.out_projs.3']
- This IS expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TransfoXLForSeq

## Label 분류의 2가지
### 단일 레이블 분류
### 멀티 레이블 분류

In [29]:
input_str = input("")

hello im student in korea


In [30]:
input_str

'hello im student in korea'

In [31]:
inputs = tokenizer(input_str, return_tensors="pt")

In [32]:
inputs

{'input_ids': tensor([[73491, 29931,  1637,     7,    24]])}

##모델에 입력값이 전달되고 logits 생성
## 이후 최종 출력값은 예측헤드로 전달되는 모든 값은 로짓이라고 함

In [33]:
with torch.no_grad():
    logits = model(**inputs).logits

predicted_class_id = logits.argmax().item()

In [49]:
logits

tensor([[-0.0162, -0.0229]])

In [34]:
predicted_class_id

1

## 만약 우리가 긍정,부정 두가지 레이블만 가진 자체 레이블을 transformer xl에 사용하고싶다면?

In [35]:
model.config.id2label #현재는 2개의 레이블만 존재

{0: 'LABEL_0', 1: 'LABEL_1'}

In [53]:
# To train a model on `num_labels` classes, you can pass `num_labels=num_labels` to `.from_pretrained(...)`
num_labels = len(model.config.id2label)
model = TransfoXLForSequenceClassification.from_pretrained("transfo-xl-wt103", num_labels=num_labels+5)

Some weights of the model checkpoint at transfo-xl-wt103 were not used when initializing TransfoXLForSequenceClassification: ['crit.out_layers.3.bias', 'crit.out_layers.0.weight', 'crit.cluster_weight', 'crit.out_layers.2.weight', 'crit.cluster_bias', 'crit.out_layers.1.weight', 'crit.out_projs.0', 'crit.out_projs.2', 'crit.out_layers.3.weight', 'crit.out_layers.1.bias', 'crit.out_projs.1', 'crit.out_layers.0.bias', 'crit.out_layers.2.bias', 'crit.out_projs.3']
- This IS expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TransfoXLForSeq

In [55]:
model.config.id2label

{0: 'LABEL_0',
 1: 'LABEL_1',
 2: 'LABEL_2',
 3: 'LABEL_3',
 4: 'LABEL_4',
 5: 'LABEL_5',
 6: 'LABEL_6'}

In [54]:
labels = torch.tensor([1])
loss = model(**inputs, labels=labels).loss

In [38]:
import torch
from transformers import AutoTokenizer, TransfoXLForSequenceClassification

## model load시 problem_type 지정

In [68]:
tokenizer = AutoTokenizer.from_pretrained("transfo-xl-wt103")
## model type
model = TransfoXLForSequenceClassification.from_pretrained("transfo-xl-wt103", problem_type="multi_label_classification",)

Some weights of the model checkpoint at transfo-xl-wt103 were not used when initializing TransfoXLForSequenceClassification: ['crit.out_layers.3.bias', 'crit.out_layers.0.weight', 'crit.cluster_weight', 'crit.out_layers.2.weight', 'crit.cluster_bias', 'crit.out_layers.1.weight', 'crit.out_projs.0', 'crit.out_projs.2', 'crit.out_layers.3.weight', 'crit.out_layers.1.bias', 'crit.out_projs.1', 'crit.out_layers.0.bias', 'crit.out_layers.2.bias', 'crit.out_projs.3']
- This IS expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TransfoXLForSeq

In [69]:
input_str = input("")

hello im student in korea


In [70]:
inputs = tokenizer(input_str, return_tensors="pt")

In [71]:
inputs

{'input_ids': tensor([[73491, 29931,  1637,     7,    24]])}

In [72]:
with torch.no_grad():
    logits = model(**inputs).logits

In [73]:
logits

tensor([[-0.1376,  0.0365]])

##모델에 입력값이 전달되고 logits 생성
## 이후 최종 출력값은 예측헤드로 전달되는 모든 값은 로짓이라고 함

In [74]:
predicted_class_ids = torch.arange(0, logits.shape[-1])[torch.sigmoid(logits).squeeze(dim=0) > 0.5]

In [75]:
predicted_class_ids # label이 일치하는것이 없으면 아예 없을수도있음

tensor([1])

## 출력되는 형태도 조정이가능한가?

In [76]:
model.config.id2label

{0: 'LABEL_0', 1: 'LABEL_1'}

In [78]:
num_labels = len(model.config.id2label)
model = TransfoXLForSequenceClassification.from_pretrained("transfo-xl-wt103", num_labels=6, problem_type="multi_label_classification")

Some weights of the model checkpoint at transfo-xl-wt103 were not used when initializing TransfoXLForSequenceClassification: ['crit.out_layers.3.bias', 'crit.out_layers.0.weight', 'crit.cluster_weight', 'crit.out_layers.2.weight', 'crit.cluster_bias', 'crit.out_layers.1.weight', 'crit.out_projs.0', 'crit.out_projs.2', 'crit.out_layers.3.weight', 'crit.out_layers.1.bias', 'crit.out_projs.1', 'crit.out_layers.0.bias', 'crit.out_layers.2.bias', 'crit.out_projs.3']
- This IS expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TransfoXLForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of TransfoXLForSeq

In [65]:
labels = torch.sum(torch.nn.functional.one_hot(predicted_class_ids[None, :].clone(), num_classes=num_labels), dim=1).to(torch.float)

In [66]:
loss = model(**inputs, labels=labels).loss