In [1]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 62.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 32.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 106.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 82.7 MB/s eta 0:00:00


In [26]:
import torch
from transformers import AutoTokenizer, ReformerForQuestionAnswering, pipeline

In [3]:
tokenizer = AutoTokenizer.from_pretrained("google/reformer-crime-and-punishment")
model = ReformerForQuestionAnswering.from_pretrained("google/reformer-crime-and-punishment")

Some weights of the model checkpoint at google/reformer-crime-and-punishment were not used when initializing ReformerForQuestionAnswering: ['lm_head.decoder.weight', 'lm_head.decoder.bias', 'lm_head.bias']
- This IS expected if you are initializing ReformerForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ReformerForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ReformerForQuestionAnswering were not initialized from the model checkpoint at google/reformer-crime-and-punishment and are newly initialized: ['reformer.encoder.layers.1.attention.self_attention.mask_value_float32', 'reformer.encoder.layers.3.attention.self_attention.self_mask_value_fl

In [31]:
generator = pipeline(model='google/reformer-crime-and-punishment',tokenizer='google/reformer-crime-and-punishment')

Some weights of ReformerModelWithLMHead were not initialized from the model checkpoint at google/reformer-crime-and-punishment and are newly initialized: ['reformer.encoder.layers.3.attention.self_attention.mask_value_float32', 'reformer.encoder.layers.1.attention.self_attention.mask_value_float16', 'reformer.encoder.layers.3.attention.self_attention.mask_value_float16', 'reformer.encoder.layers.2.attention.self_attention.mask_value_float32', 'reformer.encoder.layers.5.attention.self_attention.mask_value_float32', 'reformer.encoder.layers.4.attention.self_attention.mask_value_float32', 'reformer.encoder.layers.5.attention.self_attention.self_mask_value_float32', 'reformer.encoder.layers.2.attention.self_attention.mask_value_float16', 'reformer.encoder.layers.1.attention.self_attention.self_mask_value_float16', 'reformer.encoder.layers.4.attention.self_attention.mask_value_float16', 'reformer.encoder.layers.3.attention.self_attention.self_mask_value_float16', 'reformer.encoder.layers.5.

In [32]:
generator('How can i go to Korea',do_sample=True,temperature=0.7, max_length=100)

[{'generated_text': 'How can i go to Korea Ivanovna’s diaspected her money little feelings. And Katerina Ivanovna was on her knees, she had not drunken. She was extremely a huge in her eyes. And she was not clean casually times'}]

In [4]:
question = "What is the capital of Germany?"
text = "Germany is a country based in Europe and the captial name is Berlin."

In [5]:
inputs = tokenizer(question, text, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs)

In [33]:
inputs

{'input_ids': tensor([[152,  37, 111,  13,  21, 261, 279,  15,  94,  44, 258, 310,  16, 271,
          46, 272, 288, 258, 310,  16, 271,  46, 272, 111,   4,  21,   9, 263,
         260, 267, 272,  17,  29,  19,  39, 258, 317, 133, 262, 148,  27,  13,
          21, 261, 279, 260, 264,  94, 136, 229, 111, 187,  16, 269,   6, 278]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1]])}

In [6]:
outputs

QuestionAnsweringModelOutput(loss=None, start_logits=tensor([[-0.0291,  0.0797,  0.5960,  0.4336,  0.5308,  0.4654, -0.4657, -0.0122,
         -0.0343, -0.2123,  0.0679, -0.0219, -0.0852,  0.3755, -0.3020,  0.2130,
         -0.9640, -0.0519, -0.2662,  0.1520,  0.6527, -0.1039, -0.2224,  0.2799,
         -0.0097,  0.1714, -0.0303,  0.1726,  0.0992,  0.3307,  0.0195,  0.0980,
          0.3121, -0.0150, -0.3442,  0.0178,  0.0048, -0.2370, -0.1730,  0.2610,
         -0.4005, -0.3477, -0.1081,  0.3372, -0.5117, -0.6420, -0.0970, -0.3748,
         -0.5994, -0.1111, -0.5207, -0.5855, -0.3313, -1.3511, -0.3607, -0.5755]]), end_logits=tensor([[-0.1905,  0.0387,  0.5438, -0.1358, -0.1390,  0.0819, -0.8846, -0.5922,
         -0.6116,  0.0089, -0.7311, -0.6105, -0.7127, -0.5322, -0.7214, -0.6323,
         -1.1891, -0.2794, -0.4874, -0.4635, -0.6735, -0.5779, -0.2565, -0.4905,
          0.0803, -0.5627,  0.5918,  0.0133,  0.3806, -0.8647, -0.5059, -0.9375,
         -0.4792,  0.0177,  0.2195, -0.171

## 질문의 start index를 가져오는일

In [7]:
answer_start_index = outputs.start_logits.argmax()

In [8]:
answer_start_index

tensor(20)

In [9]:
# answer_start_index = outputs.start_logits.argmax()
answer_end_index = outputs.end_logits.argmax()

In [10]:
answer_end_index

tensor(43)

In [11]:
predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + 1]

target_start_index = torch.tensor([12])
target_end_index = torch.tensor([12])

In [12]:
target_start_index

tensor([12])

In [13]:
target_end_index

tensor([12])

In [14]:
outputs = model(**inputs, start_positions=target_start_index, end_positions=target_end_index)
loss = outputs.loss

In [15]:
loss

tensor(4.3031, grad_fn=<DivBackward0>)

In [16]:
def decode_qa_output(question, context, start_logits, end_logits, tokenizer):

    start_logits = torch.tensor(start_logits)
    end_logits = torch.tensor(end_logits)

    # Get the start and end indices with the highest logits
    start_index = start_logits.argmax()
    end_index = end_logits.argmax()

    # Get the tokens corresponding to the answer span
    tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(context))
    answer_tokens = tokens[start_index: end_index + 1]

    # Decode the answer tokens into text
    answer_text = tokenizer.convert_tokens_to_string(answer_tokens)

    # Remove special tokens or unwanted characters
    answer_text = answer_text.replace('[CLS]', '').replace('[SEP]', '').strip()

    return answer_text

In [17]:
start_logits = outputs["start_logits"]
end_logits = outputs["end_logits"]

decoded_answer = decode_qa_output(question, text, start_logits, end_logits, tokenizer)

<ipython-input-16-946d38247c86>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  start_logits = torch.tensor(start_logits)
<ipython-input-16-946d38247c86>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  end_logits = torch.tensor(end_logits)


In [36]:
decoded_answer

'urope and the captial name is Berlin.'

In [34]:
start_logits

tensor([[-0.0291,  0.0797,  0.5960,  0.4336,  0.5308,  0.4654, -0.4657, -0.0122,
         -0.0343, -0.2123,  0.0679, -0.0219, -0.0852,  0.3755, -0.3020,  0.2130,
         -0.9640, -0.0519, -0.2662,  0.1520,  0.6527, -0.1039, -0.2224,  0.2799,
         -0.0097,  0.1714, -0.0303,  0.1726,  0.0992,  0.3307,  0.0195,  0.0980,
          0.3121, -0.0150, -0.3442,  0.0178,  0.0048, -0.2370, -0.1730,  0.2610,
         -0.4005, -0.3477, -0.1081,  0.3372, -0.5117, -0.6420, -0.0970, -0.3748,
         -0.5994, -0.1111, -0.5207, -0.5855, -0.3313, -1.3511, -0.3607, -0.5755]],
       grad_fn=<CloneBackward0>)

In [35]:
end_logits

tensor([[-0.1905,  0.0387,  0.5438, -0.1358, -0.1390,  0.0819, -0.8846, -0.5922,
         -0.6116,  0.0089, -0.7311, -0.6105, -0.7127, -0.5322, -0.7214, -0.6323,
         -1.1891, -0.2794, -0.4874, -0.4635, -0.6735, -0.5779, -0.2565, -0.4905,
          0.0803, -0.5627,  0.5918,  0.0133,  0.3806, -0.8647, -0.5059, -0.9375,
         -0.4792,  0.0177,  0.2195, -0.1719, -0.5674, -0.1550,  0.3371,  0.1686,
         -0.5139, -0.5414, -0.4187,  0.6472, -0.7583, -0.1722, -0.3139, -0.8345,
         -0.0838, -0.3047, -0.2710, -0.6517,  0.1420, -0.1326,  0.0929, -0.4497]],
       grad_fn=<CloneBackward0>)

In [18]:
start_logits.argmax()

tensor(20)

In [19]:
end_logits.argmax()

tensor(43)

In [20]:
print(decoded_answer)

urope and the captial name is Berlin.
